/* Header for module bcast, generated by p2c */
#ifndef BCAST_H
#define BCAST_H

typedef unsigned char boolean;

#ifndef true
# define true    1
# define false   0
#endif

#ifndef TRUE
# define TRUE    1
# define FALSE   0
#endif

#ifdef BCAST_G
# define vextern
#else
# define vextern extern
#endif

#define FC_FILE         0x1a4   /* PARAMETER F\x9aR FCREATE (NORMAL FILE) */ 

typedef void (*bccbtype)(short chan, short free);

typedef void (*bcastprotokolltype)(char *s);

typedef void (*bcastsetpidtype)(short x, short y);

typedef void (*bcastsetmonstattype)(short x, char *s);

typedef void (*bcastsetunprototype)(short x, char *s);

typedef void (*bcastsendtype)(short x, short y, u_char *p);

typedef void (*bcasttncbuffertype)(bccbtype callback, short x);

typedef short (*bcastmonchantype)(short x);

typedef char *(*bcastgetmycalltype)(char *Result, short x);

typedef boolean (*bcastshpacsattype)(void);

typedef char *(*bcastgetdirtype)(char *Result);

typedef void (*bcastcreatestatustype)
(boolean b, char *s1, char *s2, time_t t1, time_t t2, long l, char c, char *s3);

typedef void (*bcastsortnewmailtype)(short i, char *s1, char *s2);

typedef short (*bcasthuffpackertype)
(boolean b, char *s1, char *s2, boolean b1);

typedef boolean (*bcastcheckbidtype)(char *s);

typedef boolean (*bcastbadnametype)(char *s);

typedef void (*bcastcallbacktype)(long l);

typedef void (*bcptype)(short x);

typedef void (*bcswitchtype)(short x, boolean y);


vextern bcswitchtype bcastswitchtobc;
vextern bcptype bcastpoppid, bcastpushpid, bcastpopmonstat, bcastpushmonstat,
		bcastpopunproto, bcastpushunproto;

vextern bcastshpacsattype bcastusereingabe;
vextern bcastprotokolltype bcastprotokollcall;
vextern bcastsetpidtype bcastsetpid;
vextern bcastsetmonstattype bcastsetmonstat;
vextern bcastsetunprototype bcastsetunproto;
vextern bcastsendtype bcastsend;
vextern bcasttncbuffertype bcasttncbuffer;
vextern bcastmonchantype bcastmonchan;
vextern bcastgetmycalltype bcastgetmycall;
vextern bcastshpacsattype bcastshpacsat, bcastcreaterequests;
vextern bcastcreatestatustype bcastcreatestatus;
vextern bcastsortnewmailtype bcastsortnewmail;
vextern bcasthuffpackertype bcasthuffpacker;
vextern bcastcheckbidtype bcastcheckbid;
/*  bcastbadname        :   bcastbadnametype; */

vextern bcastgetdirtype BcastTempDir, BcastSaveDir, BcastNewMailDir;


extern boolean bcast_file(u_char stnc, u_char sport, char *qrg, u_int32_t fid,
  unsigned short ftype, char *name1, char *adress, char *bbs_source,
  char *bbs_destination, char *bbs_ax25uploader, time_t bbs_upload_time,
  time_t bbs_expire_time, u_char bbs_compression, char *bbs_bid,
  char bbs_msgtype, char *bbs_title, char *bbs_fheader,
  unsigned short bodychecksum, boolean delete_after_tx,
  bcastcallbacktype *callbackproc);

extern void bcast_timing(void);
extern boolean dec_bcast(u_char pid, u_char rxtnc, char *call1, char *call2,
			 char *digipeat, unsigned short infosize,
			 u_char *inf1);
extern unsigned short decode_frameheader(u_char *inf1, unsigned short size,
					 char *sr);

#undef vextern

#endif /*BCAST_H*/

/* End. */
